Cosmetic fixes to the start and stop scripts.

diff --git a/etc/hahub/stop-hahub b/etc/hahub/stop-hahub
--- a/etc/hahub/stop-hahub
+++ b/etc/hahub/stop-hahub
@@ -1,10 +1,16 @@
 #!/bin/bash
 
 STATUS=0
-kill -15 $(cat /var/run/hahub/hahub.pid)
+ps -p `cat /var/run/hahub/hahub.pid` > /dev/null
 if [ $? -ne 0 ]; then
-	echo "Failure stopping HAHUB"
+	echo "HAHUB process not found."
 	STATUS=1
+else
+	kill -15 $(cat /var/run/hahub/hahub.pid) 2> /dev/null
+	if [ $? -ne 0 ]; then
+		echo "Failure stopping HAHUB"
+		STATUS=1
+	fi
 fi
 
 exit $STATUS
diff --git a/etc/hahub/stop-haweb b/etc/hahub/stop-haweb
--- a/etc/hahub/stop-haweb
+++ b/etc/hahub/stop-haweb
@@ -1,10 +1,17 @@
 #!/bin/bash
 
 STATUS=0
-kill -15 $(cat /var/run/hahub/haweb.pid)
+ps -p `cat /var/run/hahub/haweb.pid` > /dev/null
 if [ $? -ne 0 ]; then
-	echo "Failure stopping HAWEB"
+	echo "HAWEB process not found."
 	STATUS=1
+else
+	kill -15 $(cat /var/run/hahub/haweb.pid)
+	if [ $? -ne 0 ]; then
+		echo "Failure stopping HAWEB"
+		STATUS=1
+	fi
 fi
 
 exit $STATUS
+
