added hastart and harestart, and edited hastop. Modified hahubd.py to light-up stsLED2 when FUNC button is pressed.

diff --git a/utils/hastop b/utils/hastop
--- a/utils/hastop
+++ b/utils/hastop
@@ -1,4 +1,15 @@
 #!/bin/bash
 
+STATUS=0
 kill -15 $(cat /var/run/hahub/hahub.pid)
+if [ $? -ne 0 ]; then
+	echo "Failure"
+	STATUS=1
+fi
 kill -15 $(cat /var/run/hahub/haweb.pid)
+if [ $? -ne 0 ]; then
+	echo "Failure"
+	STATUS=1
+fi
+
+exit $STATUS
